 # Generated by Django 5.0.2 on 2024-02-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('other_skills', models.CharField(max_length=100)),
            ],
        ),
    ]
